#include <H5Cpp.h>
#include <string>
#include <iostream>

int main(){
using namespace H5;
// Generated by make_file.py
std::string fileName = "test_file.hdf5";
const H5File file(fileName, H5F_ACC_RDONLY);
auto data = file.openDataSet("dataset");
auto dataType = data.getDataType();
if (dataType.isVariableStr()) {
  H5std_string buffer;
  data.read(buffer, dataType, data.getSpace());
  std::cout<< buffer <<std::endl;
}
else {
  std::cout<< "Test string not variable length" <<std::endl;
}
return 1;
}
