#include <H5Cpp.h>
#include <iostream>
#include <sstream>
#include <string>
int main() {
  using namespace H5;
  // Generated by make_file.py
  std::string fileName = "test_file.hdf5";
  const H5File file(fileName, H5F_ACC_RDONLY);
  auto data = file.openDataSet("dataset");
  auto dataType = data.getDataType();
  unsigned int maj = 0;
  unsigned int min = 0;
  unsigned int relnum = 0;
  H5get_libversion(&maj, &min, &relnum);
  std::stringstream ss;
  ss << "lib HDF5 version " << maj << "." << min << "." << relnum;
  std::cout << ss.str() << std::endl;
  if (dataType.isVariableStr()) {
    H5std_string buffer;
    data.read(buffer, dataType, data.getSpace());
    std::cout << buffer << std::endl;
  } else {
    std::cout << "Test string not variable length" << std::endl;
  }
  return 1;
}
